### ISSUE TITLE
Apache Maven?

### ISSUE THREAD

**Issue by AmazingMech2418** [ReplAPI-it/ReplAPI.it-Java#2]
Just wondering, are you using Apache Maven for the package management? I know there are repls for Java with Maven, so that would probably be your best bet.

~~Also, any chance I could join this org and help? LOL!~~

**Comment by rayhanadev** [comment]
@AmazingMech2418 I truthfully have no clue, @EpicGamer007 is the one who will be leading this project xD.

Also glad to hear you're interested! If you're good at Java then ask @EpicGamer007 about joining this team, or if you're interested in another package/module/lib then ask the respective maintainer :D.

**Comment by abhay7dev** [comment]
i have not decided on package management yet. For the moment, i was thinking of just creating a jar file then releasing it but if someone has an account to upload the java files to maven/gradle/whatevr, you are welcome to do so.

**Comment by rayhanadev** [comment]
I just read up and Apache Maven seems amazing! Maybe consider it after you finish?

**Comment by abhay7dev** [comment]
Yeah, i definitely will. :)

**Comment by rayhanadev** [comment]
@AmazingMech2418 welcome to the team :)

**Comment by AmazingMech2418** [comment]
> @AmazingMech2418 welcome to the team :)

Thank you!
